### ISSUE TITLE
:GoDebugStart does nothing

### ISSUE THREAD

**Issue by tomesm** [fatih/vim-go#2236]
### What did you do? (required. The issue will be **closed** when not provided.)

Tried to run debugger from nvim. I have delve installed. I run: `:GoDebugBreakpoint` and then `:GoDebugStart . ` on super simple "hello world" go [file](https://pastebin.com/tu4xhCCS) (breakpoint is the ">" arrow in the pastebin code).

Delve itself is running ok on the file in my terminal. Also `:GoRun` from the nvim behaves as expected.

### What did you expect to happen?

Debugger windows appears, debugger runs and stop on breakpoint.

### What happened instead?

Two things happens randomly:

1.  Either nothing happens. After `:GoDebugStart . ` just nothing happens. Also tried `:GoDebugStart` and `:GoDebugStart hello.go` but nothing happens.

2. Or, Sometimes If i close file, open it again and try run  `:GoDebugStart` or `:GoDebugStart .`without setting breakpoint first, I got: `vim-go: could not determine package name`. If I put a breakpoint or two then the erro disappears but still nothing happens.

### Configuration (**MUST** fill this out):

* vim-go version:

* `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):

I use just vanilla init.vim. This is the only thing in it:

```
call plug#begin('~/.config/nvim/plugged')

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' } 

" Add plugins to &runtimepath
call plug#end()

```
* Vim version (first three lines from `:version`):
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
```
* Go version (`go version`):
`go version go1.11.5 darwin/amd64`
* Go environment (`go env`):
```
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/martin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/martin/Library/Mobile Documents/com~apple~CloudDocs/repos/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.5/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cr/hxzp0ksx6slbyjlgm3ttwkk00000gn/T/go-build004043882=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by bhcleek** [comment]
Literally nothing happens? You don't get the extra windows or anything?

**Comment by tomesm** [comment]
@bhcleek Yes, either literally nothing or error `vim-go: could not determine package name`.
Today I got the error message more often than yesterday. These 2 options happens somehow arbitrary.

**Comment by bhcleek** [comment]
Some issues similar to those you described were fixed a while ago. Are you using the latest master?

**Comment by tomesm** [comment]
@bhcleek I do not know how to determine version on vim-go... I've just used `Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }` I did not found anywhere in doc which version is fetched with this command.

However, I tried delete the plugin and reinstal it with the lastest v1.19 tag:

`Plug 'fatih/vim-go', { 'tag': 'v1.19' }`

And now after `GoDebugStart` Im getting: `vim-go: Vim(if):E874: (NFA) Could not pop the stack!`

**Comment by bhcleek** [comment]
The code for `:GoDebugStart` has changed significantly since v1.19. Please try using latest master.

**Comment by tomesm** [comment]
@bhcleek Ok, I reinstall nvim, removed all the plugins, reinstal vim-go with the master. This is how my init.vim looks like now:

```
call plug#begin('~/.config/nvim/plugged')

Plug 'fatih/vim-go', { 'branch': 'master' }

call plug#end()
```

But still no change. I recorded [GIF](https://giphy.com/gifs/hurwdH7SLkVegbBrJa) of the behavior.

**Comment by bhcleek** [comment]
A few pieces of information may help us figure out what's going on:

1. What's directory is the package in?
2. What's the working directory (e.g. `:echo getcwd()`)?
3. What's the output of `:messages` after running `:GoDebugStart`?

**Comment by tomesm** [comment]
1: /Users/martin/Library/Mobile Documents/com~apple~CloudDocs/repos/go/mygoprojects/debug
2: same as above...
3: "vim-go: could not determine package name"

I store my projects in iCloud outside the $GOPATH/src. But, I halso tried run debug on golang default example file: $GOPATH/src/github.com/golang/example/hello/hello.go with the same result...

**Comment by WayneYe** [comment]
+1 for this, same issue for me, I am on OSX Mojave, vim-go v1.20(commit 3e9a2920), vim version:

VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr  7 2019 10:26:49)
macOS version
Included patches: 1-1099

**Comment by bhcleek** [comment]
I'm unable to duplicate any problems with `:GoDebugStart .` when `echo getcwd()` outputs the name of the directory containing the current buffer.

The error, `vim-go: could not determine package name`, from `:GoDebugStart .` occurs in a few cases; most commonly when there is no package in the current working directory. It can also occur when you're neither in GOPATH mode nor in a directory with a relevant `go.mod` file in module mode.

**Comment by bhcleek** [comment]
@tomesm I just noticed that your directory is named `debug`. Is the package in that directory named debug? I ask, because I've seen problems in the past when trying to debug a package _named_ debug...

**Comment by bhcleek** [comment]
I was finally able to duplicate this. I'll put up a fix as soon as I have it ready.

**Comment by bhcleek** [comment]
Actually, I don't think my repro case was legitimate; I was using `:GoDebugStart .` in a working directory that did not contain a package.

**Comment by bhcleek** [comment]
@tomesm 

> I store my projects in iCloud outside the $GOPATH/src.

This will only work if your projects have a `go.mod` file. If they don't, then I would not expect `:GoDebugStart` to work well, because it won't be able to determine the package name.

> But, I have also tried run debug on golang default example file: $GOPATH/src/github.com/golang/example/hello/hello.go with the same result...

Let's focus on that basic example. Let's start simple:
1. make sure `github.com/golang/example/hello` is in GOPATH
2. `cd $(go env GOPATH)/src/github.com/golang/example/hello`
3. `vim hello.go`
4. `:GoDebugStart`

What happens?

**Comment by tomesm** [comment]
@bhcleek It does [nothing](https://giphy.com/gifs/MBJAwSVNVKYcuaDKZd)...with no imput from `:messages` this time.

I have initialy noticed this bug wen working on a project with go.mod. That's why I created a minimal init.vim with just a plugin to test it and then open this issue.

**Comment by bhcleek** [comment]
In your original bug report, what did you mean by

> Delve itself is running ok on the file in my terminal

**Comment by tomesm** [comment]
@bhcleek vim-go uses delve for debugging right? I meant that I tried to run delve debugger from terminal and it worked.

**Comment by bhcleek** [comment]
Ok, just wanted to make sure I understood that correctly. To be clear: vim-go doesn't connect to a running delve. It starts up its own delve listening on port 8181.

What does `which dlv` report on your machine?

**Comment by tomesm** [comment]
It's in $GOPATH/bin

**Comment by bhcleek** [comment]
By some chance, do you have something else listening on 127.0.0.1:8181?

**Comment by bhcleek** [comment]
In addition to the question above, I have a few more
1. After `:GoDebugStart`, is delve running on your system (and please make sure it's _not_ running before doing `:GoDebugStart`?
2. What's the output of `:echo go#config#DebugAddress()`?

**Comment by tomesm** [comment]
Ok. I'm on vacation I'll let you know by the end of next week.

**Comment by bhcleek** [comment]
@tomesm have you had a chance to investigate since vacation?

**Comment by tomesm** [comment]
@bhcleek Hi, Nothing is listening on 8181. I mean, literally nothing:

```
sudo lsof -PiTCP -sTCP:LISTEN
COMMAND    PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
rapportd   300 martin    3u  IPv4 0xd6cf1b80c4c477c1      0t0  TCP *:63559 (LISTEN)
rapportd   300 martin    4u  IPv6 0xd6cf1b80c0ddd401      0t0  TCP *:63559 (LISTEN)
postgres   622 martin    5u  IPv6 0xd6cf1b80c0ddbd01      0t0  TCP localhost:5432 (LISTEN)
postgres   622 martin    6u  IPv4 0xd6cf1b80c980a141      0t0  TCP localhost:5432 (LISTEN)
mysqld     754 martin   28u  IPv4 0xd6cf1b80c5114e41      0t0  TCP localhost:3306 (LISTEN)
mysqld     754 martin   31u  IPv6 0xd6cf1b80c0ddb181      0t0  TCP *:33060 (LISTEN)
SecomSDK 52753 martin    4u  IPv4 0xd6cf1b80d3a757c1      0t0  TCP localhost:8001 (LISTEN)
```

But dlv and delve processes are there

```
ps -ax | grep dlv
84891 ttys004    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn dlv
```

```
ps -ax | grep delve
85575 ttys004    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn delve
```

And they cannot be killed...

```
sudo kill -9 84891
kill: 84891: No such process
```

However, if I run under this circumstances 
`:GoDebugStart`
and than
`:echo go#config#DebugAddress()`
I got:
`127.0.0.1:8181`

If I run the debugger from Vscode editor I got different port number:
`Code\x20H 86475 martin   37u  IPv4 0xd6cf1b80da5c87c1      0t0  TCP localhost:51328 (LISTEN)`

**Comment by bhcleek** [comment]
Those two grep commands how that that delve is not running; the output only shows that you grepped for `dlv` and `delve`.

**Comment by bhcleek** [comment]
@tomesm Have you had a chance to run `:GoDebugStart` and then check for a running delve? Your last message indicated that you'd checked for a running delve _before_ running `:GoDebugStart`. I'm pretty sure that you're going to see that it's not running. I think the key is in your original bug report.

>  I got: vim-go: could not determine package name.

That message appears when you're in a null module (e.g. neither in GOPATH nor in a module). I suspect that the message is always appearing, but for some reason on your machine it's often overwritten before you have a chance to see it, so it only _looks_ like nothing is happening.

I'd suggest making sure that your code is either in GOPATH or else is in a module with a go.mod file.

**Comment by tomesm** [comment]
@bhcleek Indeed there is no running dlv process after `:GoDebugStart`

I have tried it in a project with go.mod file with the same "nothing happens" result.

However, If I run `:GoDebug `command I got this errors:

![Screenshot 2019-06-04 at 15 00 26](https://user-images.githubusercontent.com/6170316/58881111-c6a15d80-86d9-11e9-80d2-c55d68e9aa99.png)

Perhaps thats could tell you something more?

**Comment by bhcleek** [comment]
vim-go has no command named `:GoDebug` and no function named `godebug#debug`. It looks like you've also installed https://github.com/jodosha/vim-godebug and your issues are from that plugin.

**Comment by tomesm** [comment]
@bhcleek That was it! After removing vim-godebug the debuggers started running.

Sorry I should have noticed earlier.
