### ISSUE TITLE
golangci-lint doesn't work

### ISSUE THREAD

**Issue by delfick** [fatih/vim-go#2282]
Edit: The original issue was that my go environment wasn't setup correctly, but golangci-lint still isn't showing any errors

### What did you do? (required: The issue will be **closed** when not provided)

I set the options such that it uses golangci-lint and when I save the file it tells me

```
|| level=error msg="Running error: context loading failed: failed to load program with go/packages: unsupported version of go: exit status 2: flag provided but not defined: -compiled\nusage: list [-e] [-f format] [-json] [build flags] [packages]\nRun 'go help list' for details.\n"
```

I have in my directory two files, https://gist.github.com/delfick/98b0c05ca0507eb73f86ad685e4eb8a9

I start vim like `vim -u min main.go` where min contains

```
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
let g:go_metalinter_command='golangci-lint'
let g:go_metalinter_autosave = 1
```

### What did you expect to happen?
I expect errors to be shown!

In my real project when I manually run 

```
/Users/stephenmoore/.go/bin/golangci-lint run --print-issued-lines=false --build-tags  --disable-all --exclude-use-default=false --enable=govet --enable=golint /Users/stephenmoore/Projects/delfick/my-project/main.go
```

It successfully tells me errors in my project

### What happened instead?

Vim shows me the error mentioned above

#### vim-go version:

master branch

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
call plug#end()
let g:go_metalinter_command='golangci-lint'
let g:go_metalinter_autosave = 1
</pre></details>

#### Vim version (first three lines from `:version`):

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
```

####  Go version (`go version`):

go version go1.12.2 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/stephenmoore/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/stephenmoore/.go"
GOPROXY=""
GORACE=""
GOROOT="/Users/stephenmoore/.gimme/versions/go1.12.2.darwin.amd64"
GOTMPDIR=""
GOTOOLDIR="/Users/stephenmoore/.gimme/versions/go1.12.2.darwin.amd64/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/stephenmoore/Projects/mycompany/myproject/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/sk/1mvjp30s28l6yk7hydgkvphr0000gn/T/go-build954547482=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by delfick** [comment]
So it seems running `go env` and then starting neovim made that error go away because it adds to PATH and makes a GOROOT env variable (and made go pls start working, which wasn't working before)

But when I run `:GoMetaLinter` But it sits there doing nothing for about 10 seconds before saying `vim-go: [golangci-lint] SUCCESS` and not showing any errors even though there are errors

**Comment by bhcleek** [comment]
`go env` doesn't add anything to PATH or otherwise modify anything.

> But when I run :GoMetaLinter But it sits there doing nothing for about 10 seconds before saying vim-go: [golangci-lint] SUCCESS and not showing any errors even though there are errors

It's difficult to say without know what errors you expect to see and which linters you're using with golangci-lint on the command line. By default, `:GoMetaLinter` runs `govet`, `golint`, and `errcheck`.

**Comment by delfick** [comment]
You're right, it's not go env.

I have the following alias in my zshrc

```
function go {
    unset -f go
    source ~/.gimme/envs/go1.12.2.env
    go "$@"
}
```

Which means sourcing gimme only happens the first time I use go (the idea is to avoid delay when I open a tmux screen, but it actually seems to not take any time to source gimme, so I can probably just make that happen)

and so when I typed go env, gimme was the one changing the environment variables



As for an example of errors. Let's say my main.go looks like

```
package main

func main() {
	mt.Println("hello")
}
```

I expect 

```
 10:40 ──   /Users/stephenmoore/.go/bin/golangci-lint run --print-issued-lines=false --build-tags  --disable-all --exclude-use-default=false --enable=govet --enable=golint /Users/stephenmoore/Projects/wat/main.go
main.go:4:2: undeclared name: `mt` (typecheck)


```

I got that command from adding `echoerr join(cmd)` to https://github.com/fatih/vim-go/blob/master/autoload/go/lint.vim#L73

But vim just says success and displays no errors. I use neovim, but I just tried it with `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug 17 2018 17:24:51)` and it has the same behaviour as neovim

**Comment by delfick** [comment]
If I set it back to use gometalinter it successfully shows errors. What can I do to further figure out why vim-go isn't showing any errors from golangci-lint?

**Comment by bhcleek** [comment]
Thanks, @delfick. That may be enough for me to replicate the problem. I suspect that the errorformat string used with golangci-lint needs to be adjusted.

**Comment by bhcleek** [comment]
I _am_ able to duplicate this. 

The errorformat string seems to be correct. 

Weirdly, `golangci-lint` is exiting with a zero status from within vim-go when there are compilation errors. When run on the command line, it's existing non-zero as expected 🤔

**Comment by delfick** [comment]
hmm, that is weird

**Comment by bhcleek** [comment]
It seemed to be exiting non-zero on the command line do to an error on my part. I'd specified `--build-tags` without any arguments, so it was interpreting the next optionm, `--disable-all`, as the build tag and _not_ disabling all the checks. Once I corrected that, I do get exit code 0 from `golangci-lint` on the command line. (Of course, more checks can be enabled for use by `:GoMetaLinter` if you want by using `g:go_metalinter_enabled`.)

```
╭─bhcleek@dishrag:~/go/src/github.com/bhcleek/play/vim-go/2282 (master *%)
╰─❯❯❯ cat main.go
package foo

func main() {
        mt.Println("hello")
}
╭─bhcleek@dishrag:~/go/src/github.com/bhcleek/play/vim-go/2282 (master *%)
╰─❯❯❯ golangci-lint run --print-issued-lines=false --build-tags=''  --disable-all --exclude-use-default=false --enable=govet --enable=golint --color=never /Users/bhcleek/go/src/github.com/bhcleek/play/vim-go/2282
WARN [runner/govet] govet error: assign: analysis skipped due to errors in package
WARN [runner/govet] govet error: atomicalign: analysis skipped due to errors in package
WARN [runner/govet] govet error: bools: analysis skipped due to errors in package
WARN [runner/govet] govet error: buildtag: analysis skipped due to errors in package
WARN [runner/govet] govet error: httpresponse: analysis skipped due to errors in package
WARN [runner/govet] govet error: loopclosure: analysis skipped due to errors in package
WARN [runner/govet] govet error: ctrlflow: analysis skipped due to errors in package
WARN [runner/govet] govet error: lostcancel: failed prerequisites: ctrlflow@github.com/bhcleek/play/vim-go/2282
WARN [runner/govet] govet error: nilfunc: analysis skipped due to errors in package
WARN [runner/govet] govet error: printf: analysis skipped due to errors in package
WARN [runner/govet] govet error: shift: analysis skipped due to errors in package
WARN [runner/govet] govet error: stdmethods: analysis skipped due to errors in package
WARN [runner/govet] govet error: tests: analysis skipped due to errors in package
WARN [runner/govet] govet error: unmarshal: analysis skipped due to errors in package
WARN [runner/govet] govet error: unsafeptr: analysis skipped due to errors in package
WARN [runner/govet] govet error: unusedresult: analysis skipped due to errors in package
WARN [runner/govet] govet error: buildssa: analysis skipped due to errors in package
WARN [runner/govet] govet error: nilness: failed prerequisites: buildssa@github.com/bhcleek/play/vim-go/2282
WARN [runner] Can't run linter govet: asmdecl: analysis skipped due to errors in package
╭─bhcleek@dishrag:~/go/src/github.com/bhcleek/play/vim-go/2282 (master *%)
╰─❯❯❯ echo $?
0
```

I took another look at your original bug report and your later comment where you again referenced a `golangci-lint` command. In both cases, it looks like you made the same mistake that I'd made:

> In my real project when I manually run
> 
> /Users/stephenmoore/.go/bin/golangci-lint run --print-issued-lines=false --build-tags  --disable-all --exclude-use-default=false --enable=govet --enable=golint /Users/stephenmoore/Projects/delfick/my-project/main.go

The only item that remains, then, is why `golangci-lint` is exiting zero when it can't run `govet` due to package errors. That's an issue to take up with golangci-lint, though.

I think that covers all the concerns you had.

**Comment by delfick** [comment]
does that mean this line needs to not happen if there isn't any build tags? https://github.com/fatih/vim-go/blob/master/autoload/go/lint.vim#L272

Also, I removed that line and it still doesn't show errors in vim

**Comment by bhcleek** [comment]
That line is safe to leave in; the empty string argument is passed to `golangci-lint`. i.e.:

This is incorrect and does not accurately reflect how vim-go is calling `golangci-lint`:
```
/Users/stephenmoore/.go/bin/golangci-lint run --print-issued-lines=false --build-tags --disable-all --exclude-use-default=false --enable=govet --enable=golint /Users/stephenmoore/Projects/delfick/my-project/main.go
```

vim-go is effectively calling it like this (notice the empty string value for `--build-tags`:
```
/Users/stephenmoore/.go/bin/golangci-lint run --print-issued-lines=false --build-tags '' --disable-all --exclude-use-default=false --enable=govet --enable=golint /Users/stephenmoore/Projects/delfick/my-project/main.go
```

**Comment by delfick** [comment]
right, I got it working by setting 

```
        let g:go_metalinter_enabeld = ['deadcode', 'errcheck', 'gosimple', 'govet', 'staticcheck', 'typecheck', 'unused', 'varcheck']
```

It does seem golangci-lint is much slower than gometalinter, but that's a separate problem!

Thanks for your help!

**Comment by delfick** [comment]
actually, no, I made a change to not have --disable-all instead of enabling specific things, and it seems that list is not correct, but I'll figure it out

**Comment by delfick** [comment]
Ok, it helps if you spell the setting correctly (I had enabeld instead of enabled) and also I didn't realise there was a seperate go_metalinter_autosave_enabled. I got it to work :)
